id: PD38289A5
initial_creation_type: ocr
source_metadata:
  volumes:
    86a3ed7b88944efaad02c27bbfee5a0e:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: གཤིན་རྗེ་གཤེད་རིན་ཆེན་འབྱུང་ལྡན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1586
      volume_number: 24
